### ISSUE TITLE
Improve regular expression in get_log.py

### ISSUE THREAD

**Issue by ihkao** [upowerrobotics/ros2_fabric#30]
Currenly, there should be string "node" inside the `node_name` for `get_log.py` to get the line in log.  
Try use some other regular expression to be more flexible.

Also, the log will combine bw and freq with latency. Need revision in `get_log .py` too.

**Comment by LawrenceXu13467** [comment]
Thanks for pointing out. Please see https://github.com/upowerrobotics/ros2_fabric/pull/29/commits/c6bb357bb4a147c7d7b6ac9754fba12d92bb7a6b.
